site_name: "BTW: Blog, Tech, Wisdom"
site_url: "https://btw.suliwei.foo"

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode - more Arch-like!
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - language.selector

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: 中文
      link: /zh/
      lang: zh
    - name: 日本語
      link: /ja/
      lang: ja

nav:
  - English:
    - Home: index.md
    - Blog: blog.md
    - Weekly Reviews: weekly-reviews.md
    - Career: career.md
    - Projects: projects.md
  - 中文:
    - 主页: zh/index.md
    - 博客: zh/blog.md
    - 职业经历: zh/career.md
    - 项目: zh/projects.md
  - 日本語:
    - ホーム: ja/index.md
    - ブログ: ja/blog.md
    - 経歴: ja/career.md
    - プロジェクト: ja/projects.md
