site_name: Roland Su
site_url: https://rolandsu.com
site_author: Roland Su
site_description: Personal website and blog of Roland Su

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - toc.follow

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - footnotes
  - meta
  - attr_list
  - md_in_html

plugins:
  - search
  - tags:
      tags_file: tags.md

nav:
  - Home: index.md
  - Blog:
    - Overview: blog.md
    - Posts:
      - 'A One-Year Story Of Me, Job Finder': blog/job-search-journey.md
      - 'Two Years Experience With Arch Linux': blog/arch-linux-experience.md
      - '[Fix] Touchpad Myth': blog/touchpad-fix.md
      - 'GigaCafe: A Thought To Hackathon Activities In China': blog/gigacafe-hackathons.md
      - 'Books Reviews in February': blog/february-book-reviews.md
      - 'My First Time Hackathon': blog/my-first-hackathon.md
      - 'Some Thoughts On AI': blog/thoughts-on-ai.md
      - 'Ultimate Minimalism': blog/ultimate-minimalism.md
      - 'Healthy Life, Inspired by Bryan Johnson': blog/healthy-life-bryan-johnson.md
  - Weekly Reviews:
    - Overview: weekly-reviews.md
    - Reviews:
      - 'Week 3: Finding My Rhythm': weekly-reviews/week-3.md
      - 'Week 2: Unexpected Challenges': weekly-reviews/week-2.md
      - 'Week 1: New Beginnings': weekly-reviews/week-1.md
  - Projects: projects.md
  - About: about.md
  - Contact: contact.md
  - Tags: tags.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/liweisu0
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/liwei-su-066035350/
    - icon: fontawesome/solid/envelope
      link: mailto:liweisu59@gmail.com
